spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    hikari:
      schema: task_management
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_management
      connection-timeout: 10000

app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 60m
    refreshTokenExpiration: 30m
